theme: 
  - osuny
  - osuny-plugin-centered-header
  - osuny-plugin-centered-footer
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.png'
    footer: '/assets/images/icon.png'
  home:
    head:
      title: site
  image_sizes:
    sections:
      home:
        hero:
          mobile:   400
          tablet:   800
          desktop:  1920